### ISSUE TITLE
Tip display fails with long words

### ISSUE THREAD

**Issue by swayamraina** [webjars/wz_tooltip#1]
When a text containing a long URL is used as the content param of Tip() where the config file has a width less than required to hold the long URL in a single line, Display of Tip() is faulty.
Here, the word wrap functionality is not applied.

The tip display box somehow updates the width to what it can fit the long URL and at time of display it again reduces the width to that present in config file. Because of this only half of the text is visible i.e. the text that lies outside the width in config gets hidden.

example:

onmouseover=Tip('this text should come only half. https://this_is_really_long_url.com/some_dir/some_page.html')
config file has Tip display box width = 20 (config. Width = 20 )

**Comment by jamesward** [comment]
We don't maintain this project, just distribute it.  More info is at: http://www.walterzorn.de/tooltip/tooltip.htm
